FROM golang

RUN mkdir -p /go/src/github.com/pengliheng/golang/backend

COPY . /go/src/github.com/pengliheng/golang/backend

WORKDIR /go/src/github.com/pengliheng/golang/backend

RUN go get github.com/gorilla/mux

CMD [ "go run main.go" ]