FROM golang

RUN mkdir -p /go/src/github.com/pengliheng/golang-api/backend

COPY . /go/src/github.com/pengliheng/golang-api/backend

WORKDIR /go/src/github.com/pengliheng/golang-api/backend

RUN go get

RUN curl -fLo ~/.air https://raw.githubusercontent.com/cosmtrek/air/master/bin/linux/air

RUN chmod +x ~/.air

RUN cp ~/.air /usr/bin/air

# RUN go get github.com/gorilla/mux

# CMD [ "go run main.go" ]